version: "2"
services:
  burrow:
    build: .
    container_name: burrow
    volumes:
      - ${PWD}/docker-config:/etc/burrow/
      - ${PWD}/tmp:/var/tmp/burrow
    ports:
      - 8000:8000
  burrow_ui:
    image: generalmills/burrowui
    container_name: burrow_ui
    ports:
      - 8080:3000
    environment:
      - BURROW_HOME=http://burrow:8000/v2/kafka
    depends_on:
      - burrow