apiVersion: v1
kind: ImageStream
metadata:
  name: kafka-burrow
spec:
  dockerImageRepository: harbor.infra.tiki.services/ci/burrow
  tags:
  - from:
      kind: DockerImage
      name: 'harbor.infra.tiki.services/ci/burrow:dev'
    importPolicy:
      insecure: true
      scheduled: true
    name: dev
